### ISSUE TITLE
error when passing outlook bounce email. attached copy of html passing

### ISSUE THREAD

**Issue by sarangpatel** [crisp-oss/email-bounce-parser#1]
error when passing outlook bounce email. attached copy of html passing
[outlook.txt](https://github.com/crisp-oss/email-bounce-parser/files/13538404/outlook.txt)

**Comment by sarangpatel** [comment]
![image](https://github.com/crisp-oss/email-bounce-parser/assets/5211448/9bc36137-2ecf-458a-a1bc-7fb27981fcd6)

**Comment by sarangpatel** [comment]
html is parsing from this library - https://nodemailer.com/extras/mailparser/

**Comment by eliottvincent** [comment]
Hey! Thanks for using this library and reporting your issue. Two things here:

* you're passing the body as raw HTML, for optimal results this library only accepts a **text** body. If you use `mailparser`, you must use the `text` property from the email object. I think you're passing the `html` property right now. I've updated the README to make things more clear.
* there was also a bug in the code, I've fixed it in version [v1.0.17](https://github.com/crisp-oss/email-bounce-parser/releases/tag/v1.0.17). The library will not crash anymore, even if you pass HTML.

Regarding your example, I don't have it in my tests, so maybe some information will not be parsed. Maybe you can give me a copy of the `text` output from mailparser, so I can add it to my tests.

Let me know if thinks works for you now :)

**Comment by sarangpatel** [comment]
Thanks alot @eliottvincent  worked :)
Just wanted to confirm 2 things:
`bounce: true`  --> If its a bounched email right?
`data. recipient` -> will always contain the bounced email?

PS: Attached is outlook text body for tests.
[outlook_bounce.txt](https://github.com/crisp-oss/email-bounce-parser/files/13538909/outlook_bounce.txt)

**Comment by eliottvincent** [comment]
`bounce: true --> If its a bounched email right?`
Remember that this library doesn't **detect** bounce emails. It **only parses** them. So you need to make sure to pass bounce emails only. I guess that you receive bounce emails on a specific email address (like bounces@acme.com). You need to only pass emails that arrive to this email address.
If you pass other kind of emails, you may end up with misleading results. `bounce: false` only happens if you pass an empty body to the parser ([check here](https://github.com/crisp-oss/email-bounce-parser/blob/2dfd079bebcdde29ad93f01b6dc9b31735edb460/lib/index.js#L26-L30)).

`data. recipient -> will always contain the bounced email?`
From what I can tell, yes. I never saw a bounce email without the recipient email address inside. 

Thanks for the Outlook body, I will update the library tomorrow!

**Comment by sarangpatel** [comment]
thanks for the detail. But, the thing is,  we don't have separate email for receiving bounce emails. 

the field `error.code` ie bounce error codes, we can use to bifurcate normal vs bounce email?

**Comment by eliottvincent** [comment]
I highly recommend you to have a dedicated email address for bounces and then only parsing the mails that reach this email address.

You can use the error.code yes, but if you receive an email with `550` inside, it will be treated as a bounce, whereas it's clearly not.
What you could do is check for `data.error.code` + `data.recipient`, although you may have some false positives as well.

**Comment by sarangpatel** [comment]
got it @eliottvincent thanks

**Comment by eliottvincent** [comment]
I have released version [1.0.18](https://github.com/crisp-oss/email-bounce-parser/releases/tag/v1.0.18) that improves parsing for the Outlook example you gave me, thanks.

Let me know if you have other examples that are not correctly parsed (this library is only a few days old 😀 )
